# less awkward prefix key
set-option -g prefix C-a

# basic functionality
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# enforce 256 color terminal
set-option -g default-terminal "tmux-256color"

# theme and statusbar
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style 'rounded'
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -g status-left ""

# windows and panes
set -g base-index 1
setw -g pane-base-index 1

# move between windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# move between panes
bind -n C-S-Down select-pane -D
bind -n C-S-Left select-pane -L
bind -n C-S-Right select-pane -R
bind -n C-S-Up select-pane -U

# emulate CMD-K behaviour from macOS
bind -n C-k send-keys -R \; send-keys C-l \; clear-history

# manage panes and windows
bind C-a last-window
bind i setw synchronize-panes
bind x kill-pane

# reload tmux config
bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf

# initialize TMUX plugin manager
setenv -g TMUX_PLUGIN_MANAGER_PATH "~/.cache/tmux/plugins"
run "~/.cache/tmux/plugins/tpm/tpm"
