#!zsh

# without `do`, every argument is a directory and there is no command
local -i doidx=${argv[(Ie)do]}
(( doidx )) || doidx=$(( $# + 1 ))
local dirs=("${(@)argv[1,doidx-1]}")
local cmd=("${(@)argv[doidx+1,-1]}")

for dir in ${dirs[@]}; do
    echo -e "\n${dir:P}"
    pushd "${dir:P}" &>/dev/null
    if (( ! $#cmd )); then
        # no command: open a shell in each dir, exit it to move to the next
        zsh -i
    else
        eval "${cmd[@]}"
    fi
    popd &>/dev/null
done
