#!zsh

@inspect() {
    local var
    reply=()

    for var ($@); do
        case ${(Pt)var} in
            (*array*)
                reply+=("${var}=[${(qqq@P)var}]")
                ;;
            (*association*)
                local -a pairs=()
                local key value
                for key (${(@Pkon)var}); do
                    local pointer="${var}[${key}]"
                    pairs+=("${key}: ${(qqqP)pointer}")
                done
                reply+=("${var}={${(j:, :)${(@)pairs}}}")
                ;;
            (*)
                reply+=("${var}=${(qqqP)var}")
                ;;
        esac
    done

    return 0
}
