#!/usr/bin/env zsh
emulate -L zsh

typeset pattern="all"
if (( $# >= 1 )); then
    pattern="$1"
    shift
fi

if (( $# == 0 )); then
    set -- uptime
fi

if [[ -e "${pattern}" ]]; then
    sshp -f "${pattern}" "$@"
else
    ah "${pattern}" | sshp "$@"
fi
