#!zsh

export HOMEBREW_PREFIX="/opt/homebrew"
export HOMEBREW_BUNDLE_FILE="${XDG_CONFIG_HOME}/Brewfile"
export HOMEBREW_BUNDLE_NO_LOCK=1
export HOMEBREW_AUTO_UPDATE_SECS=86400
export HOMEBREW_CLEANUP_MAX_AGE_DAYS=7
export HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS=1
export HOMEBREW_UPDATE_REPORT_ONLY_INSTALLED=1

export HOMEBREW_SHELLENV_PREFIX= # reset
eval "$(${HOMEBREW_PREFIX}/bin/brew shellenv)"

# ensure proper GNU based environment
GNUBIN_FORMULAS=(
    coreutils
    findutils
    gawk
    gnu-sed
    gnu-tar
    gnu-time
    make
)

for formula in ${GNUBIN_FORMULAS}; do
    path=("${HOMEBREW_PREFIX}/opt/${formula}/libexec/gnubin" ${path})
    manpath=("${HOMEBREW_PREFIX}/opt/${formula}/libexec/gnuman" ${manpath})
done

alias bbd="brew bundle dump -f"
alias bz="brew uninstall --zap"

__brew_update() {
    brew update && \
    brew upgrade && \
    brew bundle install && \
    brew autoremove && \
    brew cleanup -s
}

brew() {
    command brew "$@"
}
