#!zsh

for i in {0..${1:-255}}; do
    print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}
done

for x (${(k)ZINIT}); do
    [[ $x == "col-"* ]] || continue
    +zinit-message "{${x#col-}}${x#col-}"
done
