#!zsh

if [[ $# -eq 0 ]]; then
    if [[ -n ${__die_caller} ]]; then
        print -P "%B%F{red}${__die_caller}: ${__die_message}%f%b" >&2
    fi
    typeset -g __die_caller=
    typeset -g __die_message=
else
    typeset -g __die_caller=${funcstack[2]:-${funcfiletrace[1]}}
    typeset -g __die_message="$*"

    readonly THROW

    if (( TRY_BLOCK_ERROR == 0 )); then
        (( TRY_BLOCK_ERROR = 1 ))
    fi

    THROW=  2>/dev/null
fi
