#!/usr/bin/env zsh
emulate -L zsh
[[ $TRACE -eq 1 ]] && set -x

gh-repo-list --no-archived "$@" |
    parallel --bar --tagstring "[{}]" --jobs 5 \
        git-clone-clean-main https://github.com/{} "${HOME}/src/{}"
