#!/usr/bin/env zsh
emulate -L zsh
set -e
[[ $TRACE -eq 1 ]] && set -x

typeset main latest
main="$(git main-branch)"

if [[ "$1" == "main" ]]; then
    latest="${main}"
else
    latest="$(git latest)"
fi

git checkout --quiet "${latest}"

if [[ "${latest}" == "${main}" ]]; then
    git branch --quiet --set-upstream-to="origin/${latest}"
    git pull --quiet --rebase --autostash
fi

git-cleanup
git submodule update --no-fetch --checkout --recursive
