#!/usr/bin/env zsh
emulate -L zsh
set -e
[[ $TRACE -eq 1 ]] && set -x

typeset main latest
main="$(git main-branch)"

if [[ "$1" == "main" ]]; then
    latest="${main}"
else
    latest="$(git latest)"
fi

if [[ "${latest}" == "${main}" ]]; then
    git switch --quiet "${latest}"
    git branch --quiet --set-upstream-to="origin/${latest}"
    git pull --quiet --rebase --autostash
else
    # latest is a tag; switch needs --detach to leave the branch
    git switch --quiet --detach "${latest}"
fi

git-cleanup
git submodule update --no-fetch --checkout --recursive
