#!/usr/bin/env zsh
emulate -L zsh
set -e
[[ $TRACE -eq 1 ]] && set -x

typeset repo="$1"
typeset repo_path="$2"

if [[ ! -e "${repo_path}" ]]; then
    git clone "${repo}" "${repo_path}"
fi

if [[ ! -e "${repo_path}/.noclone" ]]; then
    cd "${repo_path}"
    git cleanup
    git checkout-latest main
fi
