#!/usr/bin/env zsh
emulate -L zsh
set -e

typeset app_name="$1"; shift
typeset app_path="${HOME}/Applications/${app_name}.app"
typeset build_version="$(date +YYYYMMDDHHMMSS)"
typeset temp_path="$(mktemp -d)"

cd "${temp_path}"

nativefier \
    --name "${app_name}" \
    --build-version "${build_version}" \
    --platform mac \
    --arch x64 \
    --counter \
    --bounce \
    --fast-quit \
    "$@"

rm -rf "${app_path}"
mv ./*/*.app "${app_path}"
rm -rf "${temp_path}"

exec open "${app_path}"
