#!zsh

local id="$1" && shift || return

set -- \
atpull'brew upgrade ${ICE[id-as]}' \
atload'[[ -e "${HOMEBREW_PREFIX}/opt/${ICE[id-as]}" ]] || brew install ${ICE[id-as]}' \
atload'.path-add-gnu "${HOMEBREW_PREFIX}/opt/${ICE[id-as]}"' \
"$@"

zinit if'@is-macos' run-atpull "$@" for "${id}"
