#!/usr/bin/env zsh
emulate -L zsh

_tfe_log() { echo "$@" >&2 }

_tfe_usage() {
    _tfe_log "Usage: tfe <command>"
    _tfe_log
    _tfe_log "Commands:"
    _tfe_log "  call <method?> <path> [curl-args...]"
    _tfe_log "  local"
    _tfe_log "  agent"
    _tfe_log "  list-active-runs"
}

_tfe_is_debug() { [[ "${DEBUG}" == "1" ]] }
_tfe_log_debug() { _tfe_is_debug && _tfe_log "$@" }
_tfe_jq_debug() { _tfe_is_debug && jq "$@" }

_tfe_token() {
    jq -r '.credentials["app.terraform.io"].token' \
        "${TF_CLI_CONFIG_FILE:-${HOME}/.config/opentofu/credentials.tfrc.json}"
}

_tfe_call() {
    if [[ -z "$1" ]]; then
        _tfe_usage
        return 1
    fi
    _tfe_log_debug "-- Calling Terraform Cloud API: $*"

    typeset method="GET"
    if [[ ! "$1" =~ ^/.* ]]; then
        method="$1"
        shift
    fi

    typeset p="$1"
    shift

    curl -s "$@" \
        --request "${method}" \
        --header "Authorization: Bearer $(_tfe_token)" \
        --header "Content-Type: application/vnd.api+json" \
        "https://app.terraform.io/api/v2${p}"
}

_tfe_get_workspace_attribute() {
    typeset key="${1:?Missing key}"; shift
    typeset organization="${1:?Missing organization}"; shift
    typeset workspace="${1:?Missing workspace}"; shift

    _tfe_log_debug "-- Getting ${key} for workspace ${organization}/${workspace}"

    _tfe_call GET "/organizations/${organization}/workspaces/${workspace}" |
        jq -r ".data.attributes[\"${key}\"]"
}

_tfe_list_active_runs() {
    typeset statusList="pending,fetching,fetching_completed,pre_plan_running,pre_plan_completed,queuing,plan_queued,planning,planned,cost_estimating,cost_estimated,policy_checking,policy_override,policy_soft_failed,policy_checked,confirmed,post_plan_running,post_plan_completed,apply_queued,applying"
    typeset wsId wsName
    for wsId in $(_tfe_call /organizations/remerge/workspaces | jq -r '.data[].id'); do
        wsName=$(_tfe_call "/workspaces/${wsId}" | jq -r '.data.attributes.name')
        echo ">>> ${wsName}"
        _tfe_call "/workspaces/${wsId}/runs?filter%5Bstatus%5D=${statusList}" | \
            jq '.data | map({(.id): .attributes.status}) | add'
    done
}

() {
    typeset workspace organization
    workspace=$(basename "$PWD")
    organization=$(basename "$(dirname "$PWD")")

    if [[ -z "$1" ]]; then
        _tfe_usage
        return 1
    fi

    typeset cmd="$1"
    shift

    case "${cmd}" in
        call)
            _tfe_call "$@"
            ;;
        local)
            jq -n "{ data: { attributes: { \"execution-mode\": \"local\" } } }" |
                _tfe_call PATCH "/organizations/${organization}/workspaces/${workspace}" --data "@-" |
                _tfe_jq_debug "."
            _tfe_get_workspace_attribute execution-mode "${organization}" "${workspace}"
            ;;
        agent)
            jq -n "{ data: { attributes: { \"execution-mode\": \"agent\", \"agent-pool-id\": \"apool-RXSpmUT7izpQcWew\" } } }" |
                _tfe_call PATCH "/organizations/${organization}/workspaces/${workspace}" --data "@-" |
                _tfe_jq_debug "."
            _tfe_get_workspace_attribute execution-mode "${organization}" "${workspace}"
            ;;
        list-active-runs)
            _tfe_list_active_runs
            ;;
        *)
            _tfe_usage
            return 1
            ;;
    esac
} "$@"
