apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: stable
  pass_credentials_all: false
  password: ""
  url: https://charts.helm.sh/stable
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: grafana
  pass_credentials_all: false
  password: ""
  url: https://grafana.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: prometheus-community
  pass_credentials_all: false
  password: ""
  url: https://prometheus-community.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: cilium
  pass_credentials_all: false
  password: ""
  url: https://helm.cilium.io/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: tailscale
  pass_credentials_all: false
  password: ""
  url: https://pkgs.tailscale.com/helmcharts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: jetstack
  pass_credentials_all: false
  password: ""
  url: https://charts.jetstack.io
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: zollsoft
  pass_credentials_all: false
  password: ""
  url: https://realzollsoft.github.io/cert-manager-webhook-inwx
  username: ""
